### ISSUE TITLE
[BUG] nwg-panel hangs after period of time

### ISSUE THREAD

**Issue by kuba3351** [nwg-piotr/nwg-panel#225] opened 2023-05-17 12:07 UTC
**Describe the bug**
I can see never versions of nwg-panel started to hang on Fedora. After launch, nwg-panel works normally, but works slover over time, and then hangs completety.

**To Reproduce**
1. Run nwg-panel on Fedora 38
2. Wait some time

**Expected behavior**
Nwg-panel should not hang

**Screenshots**
While executing top, I can see something like this:
![screen-latest](https://github.com/nwg-piotr/nwg-panel/assets/6817592/4e896d02-16a9-4345-8c1b-e53c78b89c20)

**Desktop (please complete the following information):**
 - Linux distribution: Fedora 38
 - Sway version `sway -v`: 1.8.1
 - Panel version `nwg-panel -v`: 0.9.1

**Comment by nwg-piotr** [comment] 2023-05-17 12:19
Well, I've been working for 4+ hours now with 4 instances of panel running (v0.9.2, Arch), and nothing hung so far. You need to gather more info. Also upgrade the panel to the current version, if possible.

**Comment by nwg-piotr** [comment] 2023-05-17 12:40
The most wanted it the module that causes the issue. Could you try running the panel with just certain modules turned on?

**Comment by kuba3351** [comment] 2023-05-17 14:18
Ok, I used nwg-panel for a while on default config and it works fine. So, you are right that there is an issue with a module. So I will experiment with disabling module and let you know when I will investigate which module causes the problem. Thank you.

**Comment by nwg-piotr** [comment] 2023-05-17 22:46
I've been using the panel w/ sway for an hour or so. Lately it doesn't happen to me often, as I'm working on Hyprland-related stuff. One way or another, nothing hags so far. Maybe some of your executors is the culprit?

**Comment by kuba3351** [comment] 2023-05-30 08:54
I found the issue.

I ran strace to investigate what nwg-panel is doing and seen a lot of messages complaining there is no file `/home/jsierzega/.config/nwg-panel/icons_light/icon-theme.cache`. When i crfeated the file by using touch and restarted nwg-panel it works fine.

**Comment by nwg-piotr** [comment] 2023-05-30 10:36
I remember having some issue resolved by running `gtk-update-icon-cache`, but it was long time ago, and I have no idea what exactly didn't work.

**Comment by nwg-piotr** [comment] 2023-05-30 22:28
I've just added these files in default folders content. Thanks for investigating the problem.

**Comment by MoetaYuko** [comment] 2023-07-09 08:44
I assume that the root cause of this issue is incorrect uses of `Gdk.threads_add_timeout` and `GLib.timeout_add`.

We use them to schedule periodic tasks, expecting the next run to be launched after the given interval after the last run is finished, but these functions don't work in such a way. Instead, the interval specifies the time between *launches* of the task.

For instance, if a task takes 300ms to finish and the specified interval is 500ms, the time between the last finish and the next start is only 200ms. If the task takes >500ms to finish, the next run will be launched immediately after the last run is finished! This can be verified with the following program, in which the task takes 3s to finish while the interval is 1s:
```python
from gi.repository import GLib
import time


class Runner:

    def __init__(self, num_times):
        self.num_times = num_times
        self.count = 0

    def __call__(self, *args):
        self.count += 1
        print("Periodic timer [{}]: args={}".format(self.count, args))
        time.sleep(3)
        print("Periodic timer [{}] end".format(self.count))

        return self.count < self.num_times


run = Runner(5)

interval_ms = 1000
GLib.timeout_add(interval_ms, run, 'foo', 123)

loop = GLib.MainLoop()
loop.run()
```

To fix this issue, we may need to carefully revise the use of these timeout functions. I proposed #239 to fix an obvious use, which schedules the next run at the end of the current run, but it may have room for improvement.

**Comment by nwg-piotr** [comment] 2023-08-18 00:51
I assume this to be resolved. Please reopen if I'm wrong.

**Closed by nwg-piotr** 2023-08-18 00:51 UTC
