### ISSUE TITLE
[BUG] workspace window name makes panel too large

### ISSUE THREAD

**Issue by mildred** [nwg-piotr/nwg-panel#177] opened 2023-01-19 18:50 UTC
**Describe the bug**

in a configuration where the workspace list is on the top left, and the window name is shown, when the window name is too long and the screen is not so large (on a laptop screen), the large window name will force the panel to extend past the limits of the screen.

**To Reproduce**
1. Configure a new panel with:
    - workspaces on the left
    - clock on the middle 
3. Configure your screen resolution to be 1366x768
4. Open Firefox to https://github.com/nwg-piotr/nwg-panel
5. You no longer see the first workspace "1" on the list because the panel is too large

**Expected behavior**
The window name should be truncated, margins around the clock might not be so big.

**Screenshots**

Haven't found yet how to screenshoot sway :(

**Desktop (please complete the following information):**
 - Linux distribution: Fedora 37
 - Sway version `sway -v` sway version 1.7
 - Panel version `nwg-panel -v` nwg-panel version 0.7.15

**Comment by nwg-piotr** [comment] 2023-01-20 01:02
Duplicate of #95. If you REALLY need the SwayWorkspaces module in the panel that contains something in 'Center' blocks, switch off the "homogeneous" check box. 'Center' blocks will be no longer centered, however.

**Closed by nwg-piotr** 2023-01-20 01:02 UTC
