### ISSUE TITLE
[BUG] When playerctl displays Hangul characters, the tray disappears to the right of the screen

### ISSUE THREAD

**Issue by giraudan** [nwg-piotr/nwg-panel#251] opened 2023-09-11 07:50 UTC
**Describe the bug**
When playing a video whose title is in Korean, playerctl makes it scroll as expected. However, the tray and the buttons shift to the right and go outside the screen. However, the issue only shows on my laptop screen (1920x1200), not on my external monitor (2560x1440).

**To Reproduce**
1. Pick any video on your hard drive and rename it to this silly name: `[#구해줘홈즈] 이런 집이면 너무 부럽대호..😂 한옥 호텔 같은 전남 시골집🏡ㅣ#김대호 #박나래 #김숙 MBC230831방송 [G7tq27fBcyY].webm`
2. Play it so that playerctl displays it in the panel
3. See error

**Expected behavior**
I'd expect the buttons of the tray on the right hand side of the panel to be unaffected by whatever playerctl is displaying.

**Screenshots**
Here is a screenshot of my laptop screen, where we can see the issue: the wifi button is visible, the update checker is cropped, and everything else disappeared over the edge of the screen.
![image](https://github.com/nwg-piotr/nwg-panel/assets/45098592/cf3e312b-ca47-4c05-97cd-39e1f2740396)

Here is a screenshot of my external screen, where there's no issue:
![image](https://github.com/nwg-piotr/nwg-panel/assets/45098592/07a3c34d-cc51-4131-a6a7-b905084d9854)

**Desktop (please complete the following information):**
 - Linux distribution: Arch
 - Sway version `sway -v`: `sway version 1.8.1`
 - Panel version `nwg-panel -v`: `nwg-panel version 0.9.12`

**Additional context**
I can record my desktop with `wf-recorder` and post it if relevant.

**Comment by nwg-piotr** [comment] 2023-09-11 07:53
Duplicate of #95 and several other. Please read https://github.com/nwg-piotr/nwg-panel/issues/95#issuecomment-1053973777

**Closed** 2023-09-11 07:53 UTC
