### ISSUE TITLE
[BUG] panel width is slightly too wide (2 screens?)

### ISSUE THREAD

**Issue by japhir** [nwg-piotr/nwg-panel#102] opened 2022-04-07 11:50 UTC
**Describe the bug**
My slightly modified version of the top panel of preset-1 shows a bunch of elements, but the left-most widget is cut off from the screen and so is the part on the right. It might also be related to the sway-taskbar not showing up on my primary display currently, even though I've set the bar to display on "all".

**To Reproduce**
1. select preset-1
2. have 2 screens, with the top bar set to "all"
3. add the sway-taskbar to modules-left
4. I've changed the date format to be slightly more informative
5. add a custom module for the center of the bar, with bash-fuzzy-clock
6. see problem in image

**Expected behavior**
The bar should fit to the width of the screen. To the left of the firefox icon there's still a workspace 1 with a terminal and a workspace 2 name. To the right is the remainder of the panel button.

**Screenshots**
![2022-04-07-13:47:33](https://user-images.githubusercontent.com/10659193/162191988-d1c5b1d2-a9fa-4868-9905-51c9686a480c.png)

**Desktop (please complete the following information):**
 - Linux distribution: Arch Linux x86_64 (Kernel 5.17.1-arch1-1)
 - Sway version 1.7
 - Panel version 0.6.2

**Comment by nwg-piotr** [comment] 2022-04-07 12:09
[Closed as duplicate of #95]

Sorry, but it's a feature, not a bug. ;) Or a bug which may be never fixed.

The problem appears when you use Center modules together with a wide Left or Right block. If we want the Center content to be centered in the screen, we need Left, Center and Right modules container to be [homogeneous](https://lazka.github.io/pgi-docs/Gtk-3.0/classes/Box.html#Gtk.Box.set_homogeneous). If you want some content in the Center, you need to use less content in side containers. Sorry, but I have no better idea at the time.

**Closed by nwg-piotr** 2022-04-07 12:09 UTC

**Comment by japhir** [comment] 2022-04-07 12:27
Ah sorry, I had seen the other issue as well but thought it had a different cause.

Ok I've removed the time from the clock block and now it's fine. It surprised me that this shifts the blocks when there was still space enough on both sides of the fuzzy-clock. On a sidenote, do you plan to at some point also rewrite this module into go?

**Comment by nwg-piotr** [comment] 2022-04-07 12:39
I considered it in the very beginning, and asked contributors of my previous stuff what they thought. The conclusion was: in this certain case the performance is less important than the ease of code maintenance.

BTW: [my last production](https://github.com/nwg-piotr/nwg-look) could have been written in python as well. I chose golang, however, for fear that I would eventually forget even the basics. I haven't touched go for over six months. 🤣
