### ISSUE TITLE
[BUG] tray icons show up as blank spaces and don't function

### ISSUE THREAD

**Issue by b-** [nwg-piotr/nwg-panel#254] opened 2023-10-04 17:59 UTC
**Describe the bug**
When I launch an application that I expect to deposit a tray icon, an unclickable blank space appears instead. I'm using a pretty standard install of Arch + Sway + nwg-shell from AUR (installed with yay via `yay -S nwg-shell`).

**To Reproduce**
1. Install Arch
2. Install `yay` from AUR
3. `yay -S nwg-shell`
4. `nwg-shell-installer` and consent to replacing your sway config
5. `yay -S 1password keybase-gui`
6. Try running either 1Password or Keybase, and notice that a tray-icon sized blank space appears in the panel where I'd expect the tray icon to go. 

This blank space also can't be clicked on, and if I reload the config and restart the bars with meta+shift+c it disappears.

**Expected behavior**
Tray icons should work

**Screenshots**
![screenshot](https://github.com/nwg-piotr/nwg-panel/assets/284789/69f5199a-40df-4c70-a2e1-ec347e7c3fa5)

**Desktop (please complete the following information):**
 - Arch
 - `sway version 1.8.1`
 - Panel version `nwg-panel version 0.9.13`

**Additional context**
I tried both the stable versions of nwg-shell and nwg-panel from the AUR, but also the `-git` versions as well (`yay -Rdd nwg-panel && yay -S nwg-panel-git`). It didn't make a difference.

**Comment by b-** [comment] 2023-10-04 18:01
I feel like I'm not providing enough specific/helpful information, but I honestly have no idea how to further debug this sort of thing. AppIndicators and the like always seemed a little like voodoo to me (especially with there being both AppIndicators and KStatusNotifierItems and so on... I really don't know anything about how that works)

**Comment by nwg-piotr** [comment] 2023-10-04 22:37
Sorry, but this affects all Electron apps since some update, and nobody knows how to fix it. Closing as duplicate of #224 #248

**Closed by nwg-piotr** 2023-10-04 22:37 UTC
